doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_0900_ai_ci
        mapping_types:
            enum: string
            bit: integer
        types:
            uuid:
                class: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Api:
                type:      xml
                dir:       "%kernel.project_dir%/src/Api/Infrastructure/Persistence/Doctrine/mapping"
                alias:     Api
                prefix:    Quote\Api\Domain\Model
                is_bundle: false
