services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  quote.api.controller.ping:
    class: Quote\Api\Infrastructure\UI\Controller\Ping\PingController

  quote.api.controller.get.shouts.by.author:
    class: Quote\Api\Infrastructure\UI\Controller\GetShoutsByAuthor\GetShoutsByAuthorController
    arguments:
      - '@query.bus'