services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  quote.api.query.get.shouts.by.author:
    class: Quote\Api\Application\Query\GetShoutsByAuthor\GetShoutsByAuthorQueryHandler
    arguments:
      - '@rabbitmq.publisher'
      - '@quote.api.doctrine.author.repository'
      - '@quote.api.doctrine.quote.repository'
      - '@redis.repository'
      - '@php.serializer'