services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  quote.api.doctrine.author.repository:
    class: Quote\Api\Infrastructure\Persistence\Doctrine\Author\DoctrineAuhorRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Quote\Api\Domain\Model\Author\Author

  quote.api.doctrine.quote.repository:
    class: Quote\Api\Infrastructure\Persistence\Doctrine\Quote\DoctrineQuoteRepository
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - Quote\Api\Domain\Model\Quote\Quote